name: PR Sanity Check

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          npm install

      - name: Lint check
        run: |
          npm run lint

      - name: Prepare docker
        run: docker pull yukinying/chrome-headless-browser:90.0.4408.0

      - name: build story book
        run:  npm run build-storybook

      - name: run loki test
        run: |
          npm run loki-test
