name: Sanity Check && Test && Deploy to GHP

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          npm install

      - name: Lint check
        run: |
          npm run lint

      - name: Prepare docker
        run: docker pull yukinying/chrome-headless-browser:90.0.4408.0

      - name: build story book
        run: npm run build-storybook

      - name: run loki test
        run: |
          npm run loki-test

      - name: Deploy
        # https://github.com/marketplace/actions/deploy-to-github-pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

